# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "a70fa8cb537266ff4040dcf5baca3662"
name = "insurance-upsell-product"
handle = "insurance-upsell-product"
application_url = "https://ones-trademarks-twist-segments.trycloudflare.com"
embedded = true

[build]
automatically_update_urls_on_dev = true
dev_store_url = "insurance-upsell.myshopify.com"
include_config_on_deploy = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products"

[auth]
redirect_urls = [
  "https://ones-trademarks-twist-segments.trycloudflare.com/auth/callback",
  "https://ones-trademarks-twist-segments.trycloudflare.com/auth/shopify/callback",
  "https://ones-trademarks-twist-segments.trycloudflare.com/api/auth/callback"
]

[webhooks]
api_version = "2024-04"

[pos]
embedded = false
