# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "543ec1b60143f43276af6b1176042039"
name = "insurance-upsell-product"
handle = "insurance-upsell-product-1"
application_url = "https://existence-powerseller-beauty-maximum.trycloudflare.com"
embedded = true

[build]
automatically_update_urls_on_dev = true
dev_store_url = "ensurance-extension.myshopify.com"
include_config_on_deploy = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products"

[auth]
redirect_urls = [
  "https://existence-powerseller-beauty-maximum.trycloudflare.com/auth/callback",
  "https://existence-powerseller-beauty-maximum.trycloudflare.com/auth/shopify/callback",
  "https://existence-powerseller-beauty-maximum.trycloudflare.com/api/auth/callback"
]

[webhooks]
api_version = "2024-04"

[pos]
embedded = false
